name: ranger-server
initialRotationStatus: false

rangerConfiguration:
  namespace: phonepe
  zookeeper: stg-appzk001.phonepe.nb6:2181,stg-appzk002.phonepe.nb6:2181,stg-appzk003.phonepe.nb6:2181
  disablePushUpdaters: true

server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 7080
  adminConnectors:
    - type: http
      port: 7081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO

  loggers:
    io.appform.ranger.server: DEBUG

  appenders:
    - type: console
      threshold: INFO
      timeZone: IST
      logFormat: "%(%-5level) [%date] [%thread] [%logger{0}]: %message%n"


